import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by platzi" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>

      <footer></footer>
    </div>
  );
}
