import Head from "next/head";
import { useState } from "react";
import type { MouseEventHandler } from "react";

import { LazyImage } from "@/components/RandomFox";

// random fuction between 1 and 123
const random = () => Math.floor(Math.random() * 123 + 1);

// simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

type ImageItem = { id: string; url: string };

export default function Home() {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`,
    };

    setImages([...images, newImageItem]);
  };

  return (
    <div>
      <Head>
        <title>Random Fox</title>
        <meta name="description" content="Generated by platzi" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }, index) => (
          <div key={id} className="p-4">
            <LazyImage
              className="rounded-lg bg-gray-300"
              src={url}
              width={320}
              height="auto"
              onClick={() => console.log("hey")}
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo: `, img);
              }}
            />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
}
